### ISSUE TITLE
大神，能否增加单容器监控功能？

### ISSUE THREAD

**Issue by lorock** [Mr-Linus/DCMP#3]
大神，能否增加单容器监控功能？监控数据建议写入数据库，以曲线图的形式显示出来。

**Comment by Mr-Linus** [comment]
有在考虑，我们会尽力完成，感谢issue！

**Comment by Mr-Linus** [comment]
已经支持单个监控容器监控功能 @lorock 
<https://github.com/Mr-Linus/DCMP/commit/ce4990bbb5a05f27b21f3cba3742c8decf76b167> #
