### ISSUE TITLE
容器能否自定义网络

### ISSUE THREAD

**Issue by zoushiwen** [Mr-Linus/DCMP#5]
如果用 docker-compose 启动应用，需要考虑容器的网络问题；比如用docker-compose启动 lnmp 应用，就需要考虑把lnmp放在同一网络中；

**Comment by Mr-Linus** [comment]
Thank you for your issue. I have implemented this function in <https://github.com/Mr-Linus/DCMP/commit/a130fbeb0e2bd9f4f92786da6372c484f3356921>. @zoushiwen
